### ISSUE TITLE
Use globally on Linux

### ISSUE THREAD

**Issue by thatsthat** [Thertzlor/epub-print-page-approximator#2]
First of all thanks for this tool, it allows me to read my ebooks on a plethora of different devices with KOreader installed, and having device independent page numbers is very handy.

Currently I get an error if I call page_approximator.py from a different folder. Do you know if there is any way to install this tool globally on Linux?

**Comment by Thertzlor** [comment]
Are you sure that this is a Linux specific issue?
If you are just using the script I don't think it can be used "globally" on windows either, that's just the way python imports work.

You could try changing the working directory just before calling the script.

**Comment by thatsthat** [comment]
Ok, thanks for the info! By the way, this could be turned into a very useful plugin for [Calibre](https://calibre-ebook.com/)

**Comment by thatsthat** [comment]
Ok, thanks for the info! By the way, this could be turned into a very useful plugin for [Calibre](https://calibre-ebook.com/)
